### ISSUE TITLE
Duplicate Articles

### ISSUE THREAD

**Issue by AngleV** [Pkmmte/PkRSS#14]
its time i call PkRSS.with(getActivity()).get(category.getUrl(), search); i get duplicate articles in List.

Why is this happen ?

**Comment by GerhardPue** [comment]
It seams, we get the same issue! 

when  i log .. the articleList.size().... with every run(I use a service) the size gets bigger and bigger ...

but if i call   PkRSS.with(this).clearCache();

on the next run i get the error:


W/System.err﹕ java.lang.IllegalStateException: cache is closed
W/System.err﹕ at com.squareup.okhttp.internal.DiskLruCache.checkNotClosed(DiskLruCache.java:612)
W/System.err﹕ at com.squareup.okhttp.internal.DiskLruCache.get(DiskLruCache.java:400)
W/System.err﹕ at com.squareup.okhttp.Cache.get(Cache.java:158)
W/System.err﹕ at com.squareup.okhttp.Cache$1.get(Cache.java:117)
W/System.err﹕ at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:221)
W/System.err﹕ at com.squareup.okhttp.Call.getResponse(Call.java:198)
W/System.err﹕ at com.squareup.okhttp.Call.execute(Call.java:80)
W/System.err﹕ at com.pkmmte.pkrss.downloader.OkHttpDownloader.execute(OkHttpDownloader.java:80)
W/System.err﹕ at com.pkmmte.pkrss.PkRSS.load(PkRSS.java:159)
W/System.err﹕ at com.pkmmte.pkrss.RequestCreator$1.doInBackground(RequestCreator.java:168)
W/System.err﹕ at com.pkmmte.pkrss.RequestCreator$1.doInBackground(RequestCreator.java:164)
W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err﹕ at java.lang.Thread.run(Thread.java:818)

**Comment by Pkmmte** [comment]
What URL are you trying this on that returns duplicates?

**Comment by karosas** [comment]
Got same/similar bug. With every consecutive call to same rss url it returns duplicated list with increasing amount of duplicates per request. For example at first request its 25, 2nd - 50, 3rd - 75 and so on.

**Comment by Pkmmte** [comment]
Currently in the process of completely refactoring PkRSS with support for custom cache modules. The refactor will include a fix for duplicates.

**Comment by feidi2014** [comment]
@Pkmmte when do you plan to release 2.0.0?
